name: 'Test, Build, Upload artifact, and Deploy'
'on': workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.318
      - name: Build and test
        run: dotnet build --configuration Release
  release:
    runs-on: ubuntu-latest
    needs: test
    name: 'Build, package, and upload .dll artifact'
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.318
      - name: Build and package project
        run: dotnet publish --configuration Release --output ./publish
      - name: Show contents of the current working directory
        run: ls -la
      - name: Show contents of the publish directory
        run: ls -la ./publish
      - name: Upload .NET build artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./publish
  deploy:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.318
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: '${{ secrets.ACTIONS_DEPLOY }}'
